// <auto-generated />
namespace CarServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class vehicleinfoisaddedintoOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vehicleinfoisaddedintoOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181005088_vehicle info is added into Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
